# Generated by Django 5.2.7 on 2025-11-21 15:17

import cyberthreatexchange.server.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', cyberthreatexchange.server.models.IdentityIDField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(default='identity', max_length=10)),
                ('spec_version', models.CharField(default='2.1', max_length=3)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('revoked', models.BooleanField(default=False)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=32, null=True)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('identity_class', models.CharField(max_length=64)),
                ('sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('contact_information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('collection_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('last_run', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.identity')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bundle-upload', 'Bundle Upload'), ('single-upload', 'Single Upload'), ('single-delete', 'Single Delete')])),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')])),
                ('payload', models.JSONField(default=None, null=True)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('warnings', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField(default=None, null=True)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.feed')),
            ],
        ),
    ]
