# Generated by Django 5.2.7 on 2026-01-05 12:05

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogesec_identity', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('collection_name', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=140, null=True)),
                ('short_description', models.CharField(blank=True, max_length=512, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('last_run', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('other', 'Other'), ('apt_group', 'Apt Group'), ('vulnerability', 'Vulnerability'), ('data_leak', 'Data Leak'), ('malware', 'Malware'), ('ransomware', 'Ransomware'), ('infostealer', 'Infostealer'), ('threat_actor', 'Threat Actor'), ('campaign', 'Campaign'), ('exploit', 'Exploit'), ('cyber_crime', 'Cyber Crime'), ('indicator_of_compromise', 'Indicator Of Compromise'), ('ttp', 'Ttp')], max_length=128), blank=True, default=list, size=None)),
                ('identity', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogesec_identity.identity')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bundle-upload', 'Bundle Upload'), ('single-upload', 'Single Upload'), ('single-delete', 'Single Delete')])),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')])),
                ('payload', models.JSONField(default=None, null=True)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('warnings', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completion_time', models.DateTimeField(default=None, null=True)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.feed')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(max_length=255)),
                ('stix_type', models.CharField(max_length=100)),
                ('modified', models.DateTimeField()),
                ('value', models.TextField(db_index=True)),
                ('value_type', models.CharField(max_length=100)),
                ('is_ref', models.BooleanField(default=False)),
                ('ref_stix_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.feed')),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'value'], name='cyberthreat_feed_id_d5c5d0_idx'), models.Index(fields=['feed', 'stix_id', 'modified'], name='cyberthreat_feed_id_b2d82a_idx'), models.Index(fields=['feed', 'ref_stix_id'], name='cyberthreat_feed_id_1c3bdb_idx'), models.Index(fields=['feed', 'is_ref'], name='cyberthreat_feed_id_8585b9_idx')],
                'unique_together': {('feed', 'stix_id', 'modified', 'value', 'value_type', 'is_ref', 'ref_stix_id')},
            },
        ),
    ]
