# Generated by Django 5.2.7 on 2026-01-13 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('bundle-upload', 'Bundle Upload'), ('connector-pull', 'Connector Poll'), ('single-upload', 'Single Upload'), ('single-delete', 'Single Delete')]),
        ),
        migrations.AddField(
            model_name='job',
            name='extra',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('taxii', 'Taxii')], default='taxii', editable=False, max_length=50)),
                ('taxii_collection_url', models.URLField(max_length=500)),
                ('enc_user', models.TextField(blank=True, null=True)),
                ('enc_pass', models.TextField(blank=True, null=True)),
                ('last_completion_time', models.DateTimeField(blank=True, null=True)),
                ('next_run_added_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='cyberthreatexchange.feed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
