# Generated by Django 5.2.7 on 2026-01-14 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0002_alter_job_type_connector'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnprocessedRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(max_length=255)),
                ('target_ref', models.CharField(max_length=255)),
                ('source_ref', models.CharField(max_length=255)),
                ('stix_data', models.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.job')),
            ],
        ),
    ]
