# Generated by Django 5.2.9 on 2026-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0003_unprocessedrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
