# Generated by Django 5.2.7 on 2026-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0004_alter_feed_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='taxii_collection_url',
            new_name='url',
        ),
    ]
