# Generated by Django 5.2.9 on 2026-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0005_rename_taxii_collection_url_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
