# Generated by Django 5.2.11 on 2026-03-17 14:20

from django.db import migrations, models


def truncate_short_descriptions(apps, schema_editor):
    """Truncate all short_description fields to 140 characters before applying max_length constraint."""
    Feed = apps.get_model('cyberthreatexchange', 'Feed')
    for feed in Feed.objects.all():
        if feed.short_description and len(feed.short_description) > 140:
            feed.short_description = feed.short_description[:140]
            feed.save(update_fields=['short_description'])


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0006_alter_connector_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, max_length=720, null=True),
        ),
        migrations.RunPython(truncate_short_descriptions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feed',
            name='short_description',
            field=models.CharField(default='[BLANK]', max_length=140),
            preserve_default=False,
        ),
    ]
