# Generated by Django 5.2.12 on 2026-03-31 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0007_alter_feed_description_alter_feed_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectValue',
        ),
        migrations.CreateModel(
            name='NewObjectValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(db_index=True, max_length=128)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('modified', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('values', models.JSONField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.feed')),
            ],
            options={
                'indexes': [models.Index(fields=['stix_id', 'modified'], name='cyberthreat_stix_id_3d20fe_idx'), models.Index(fields=['feed', 'stix_id'], name='cyberthreat_feed_id_da51a5_idx')],
                'unique_together': {('feed', 'stix_id')},
            },
        ),
        migrations.CreateModel(
            name='ObjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stix_id', models.CharField(db_index=True, max_length=255)),
                ('modified', models.DateTimeField(null=True)),
                ('added_at', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberthreatexchange.feed')),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'stix_id'], name='cyberthreat_feed_id_1c6158_idx'), models.Index(fields=['feed', 'modified'], name='cyberthreat_feed_id_987abb_idx')],
                'unique_together': {('feed', 'stix_id', 'modified')},
            },
        ),
    ]
