# Generated by Django 5.2.12 on 2026-03-31 12:53

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0009_value_related_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_values_concat(j jsonb)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT string_agg(LOWER(value), ' ')
                FROM jsonb_each_text(j)
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_sort_value(j jsonb)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT SUBSTR(LOWER(value), 0, 32)
                FROM jsonb_each_text(j)
                LIMIT 1
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]