# Generated by Django 5.2.12 on 2026-04-03 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0010_fix_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='newobjectvalue',
            name='is_dupe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newobjectvalue',
            name='values_concat',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), function='jsonb_values_concat'), null=True, output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='newobjectvalue',
            name='values_list',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), function='jsonb_values_list'), null=True, output_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
        ),
        migrations.AddField(
            model_name='newobjectvalue',
            name='values_sort',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), function='jsonb_sort_value'), null=True, output_field=models.CharField(max_length=32)),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'stix_id'], name='ctx_nov_type_stix_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'type'], name='ctx_nov_created_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'type'], name='ctx_nov_modified_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['values_sort', 'type'], name='ctx_nov_values_concat_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(fields=['is_dupe'], name='ctx_nov_empty_query_idx'),
        ),
    ]
