# Generated by Django 5.2.12 on 2026-04-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cyberthreatexchange",
            "0011_newobjectvalue_is_dupe_newobjectvalue_values_concat_and_more",
        ),
    ]
    atomic = False

    operations = [
        migrations.RunSQL(
            """
                DROP INDEX IF EXISTS ctx_values_list_idx;
                CREATE INDEX ctx_values_list_idx
                ON cyberthreatexchange_newobjectvalue
                USING gin (values_list array_ops, type gin_trgm_ops) WHERE NOT is_dupe;
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS ctx_values_concat_idx;
                CREATE INDEX ctx_values_concat_idx
                ON cyberthreatexchange_newobjectvalue
                USING gin (values_concat gin_trgm_ops, type gin_trgm_ops) WHERE NOT is_dupe;
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql="""
                --- ensure the new indexes have accurate statistics for the query planner before we rely on them in production queries
                VACUUM ANALYZE cyberthreatexchange_newobjectvalue;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
