# Generated by Django 5.2.13 on 2026-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0012_more_manual_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='short_description',
            field=models.CharField(max_length=512),
        ),
    ]
