# Generated by Django 5.2.12 on 2026-04-30 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0013_alter_feed_description_alter_feed_short_description'),
    ]

    operations = [

        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_hash_values_list(j jsonb)
            RETURNS uuid[]
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT array_agg(md5(LOWER(value))::uuid)
                FROM jsonb_each_text(j)
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS jsonb_hash_values_list(jsonb);",
        ),
        migrations.RemoveField(
            model_name='newobjectvalue',
            name='values_list',
        ),
        migrations.AddField(
            model_name='newobjectvalue',
            name='hashed_values_list',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), function='jsonb_hash_values_list'), null=True, output_field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
        ),
        migrations.RunSQL(
            """
                DROP INDEX IF EXISTS ctx_values_list_idx;
                CREATE INDEX ctx_values_list_idx
                ON cyberthreatexchange_newobjectvalue
                USING gin (hashed_values_list array_ops, type gin_trgm_ops) WHERE NOT is_dupe;
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
