# Generated by Django 5.2.12 on 2026-05-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0014_newobjectvalue_hashed_values_list'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION jsonb_sort_value(j jsonb, extra_text text)
            RETURNS text
            LANGUAGE sql
            IMMUTABLE
            PARALLEL SAFE
            AS $$
                SELECT SUBSTR(SUBSTR(LOWER(value), 1, 32) || '+' || extra_text, 0, 48)
                FROM jsonb_each_text(j)
                LIMIT 1
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
