# Generated by Django 5.2.12 on 2026-05-08 15:28

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0015_update_functions_and_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_created_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_modified_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_created_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_modified_kb_idx',
        ),
        ## recreate values_sort
        migrations.RemoveField(
            model_name='newobjectvalue',
            name='values_sort',
        ),
        migrations.AddField(
            model_name='newobjectvalue',
            name='values_sort',
            field=models.GeneratedField(db_persist=True, expression=models.Func(models.F('values'), django.db.models.functions.comparison.Cast(models.F('id'), models.TextField()), function='jsonb_sort_value'), null=True, output_field=models.CharField(max_length=48)),
        ),
        ## recreate indexes
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'id', 'type', 'feed_id'], name='ctx_nov_created_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'id', 'type', 'feed_id'], name='ctx_nov_modified_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['created', 'id', 'knowledgebase', 'feed_id'], name='ctx_nov_created_kb_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['modified', 'id', 'knowledgebase', 'feed_id'], name='ctx_nov_modified_kb_idx'),
        ),
    ]
