# Generated by Django 5.2.12 on 2026-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0016_remove_newobjectvalue_ctx_nov_created_type_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='objectversion',
            name='cyberthreat_feed_id_1c6158_idx',
        ),
        migrations.RenameIndex(
            model_name='newobjectvalue',
            new_name='ctx_nov_values_sort_type_idx',
            old_name='ctx_nov_values_concat_idx',
        ),
        migrations.RenameIndex(
            model_name='newobjectvalue',
            new_name='ctx_nov_values_sort_kb_idx',
            old_name='ctx_nov_values_kb_idx',
        ),
        migrations.AlterField(
            model_name='objectversion',
            name='stix_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='objectversion',
            index=models.Index(fields=['stix_id', 'feed_id'], name='ctx_version_feed_idx'),
        ),
    ]
