# Generated by Django 5.2.12 on 2026-05-14 11:58

import datetime
from django.db import connection, migrations, models


def modify_dates(apps, schema_editor):
    total = 0
    start_time = datetime.datetime.now()
    print(" started at:", str(start_time))
    while True:
        with connection.cursor() as cursor:
            round_start = datetime.datetime.now()

            cursor.execute("""
                UPDATE cyberthreatexchange_newobjectvalue
                SET
                created = '1970-01-01'::timestamptz,
                modified = '1970-01-01'::timestamptz
                WHERE id IN (
                SELECT id FROM cyberthreatexchange_newobjectvalue
                WHERE created IS NULL OR modified IS NULL
                LIMIT 10000
                )
                RETURNING id;
            """)
            total += cursor.rowcount
            print(
                "\t\t\t",
                ">> updated",
                cursor.rowcount,
                "rows in",
                str(datetime.datetime.now() - round_start),
                "total elapsed time:",
                str(datetime.datetime.now() - start_time),
                "total rows:",
                total,
            )
            if cursor.rowcount == 0:
                break
    print("completed at:", str(datetime.datetime.now()))


class Migration(migrations.Migration):

    dependencies = [
        (
            "cyberthreatexchange",
            "0017_remove_objectversion_cyberthreat_feed_id_1c6158_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS ctx_values_concat_idx;
            CREATE INDEX temp_index_modified_idx ON cyberthreatexchange_newobjectvalue (id) WHERE (modified IS NULL OR created IS NULL);
        """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(modify_dates, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS temp_index_modified_idx;
            CREATE INDEX ctx_values_concat_idx ON cyberthreatexchange_newobjectvalue USING gin (values_concat gin_trgm_ops, type gin_trgm_ops) WHERE (NOT is_dupe);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="newobjectvalue",
            index=models.Index(
                condition=models.Q(("is_dupe", False)),
                fields=["feed", "stix_id"],
                name="ctx_deduplicator_idx",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="newobjectvalue",
                    name="created",
                    field=models.DateTimeField(
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                migrations.AlterField(
                    model_name="newobjectvalue",
                    name="modified",
                    field=models.DateTimeField(
                        default=datetime.datetime(
                            1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                ALTER TABLE cyberthreatexchange_newobjectvalue
                    ALTER COLUMN created SET DEFAULT '1970-01-01'::timestamptz,
                    ALTER COLUMN created SET NOT NULL,
                    ALTER COLUMN modified SET DEFAULT '1970-01-01'::timestamptz,
                    ALTER COLUMN modified SET NOT NULL;
                """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="newobjectvalue",
                    name="values_sort",
                    field=models.GeneratedField(
                        db_persist=True,
                        expression=models.Func(
                            models.F("values"),
                            models.functions.comparison.Cast(
                                models.F("id"), models.TextField()
                            ),
                            function="jsonb_sort_value",
                        ),
                        null=True,
                        output_field=models.CharField(max_length=69),
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                ALTER TABLE cyberthreatexchange_newobjectvalue
                    ALTER COLUMN values_sort TYPE varchar(69);
                """,
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
        ),
        migrations.RenameIndex(
            model_name="newobjectvalue",
            new_name="ctx_nov_feed_stix_idx",
            old_name="cyberthreat_feed_id_da51a5_idx",
        ),
    ]
