# Generated by Django 5.2.12 on 2026-05-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0018_alter_newobjectvalue_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newobjectvalue',
            name='arango_pk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ObjectVersion',
        ),
    ]
