# Generated by Django 5.2.12 on 2026-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0019_newobjectvalue_arango_pk_delete_objectversion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_created_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_modified_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_created_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_modified_kb_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_values_sort_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='newobjectvalue',
            name='ctx_nov_values_sort_kb_idx',
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'feed_id', '-created', '-id'], name='ctx_nov_created_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'feed_id', '-modified', '-id'], name='ctx_nov_modified_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'feed_id', 'values_sort'], name='ctx_nov_values_sort_type_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['knowledgebase', 'feed_id', '-created', '-id'], name='ctx_nov_created_kb_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['knowledgebase', 'feed_id', '-modified', '-id'], name='ctx_nov_modified_kb_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['knowledgebase', 'feed_id', 'values_sort'], name='ctx_nov_values_sort_kb_idx'),
        ),
    ]
