# Generated by Django 5.2.12 on 2026-06-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberthreatexchange', '0019_newobjectvalue_arango_pk_delete_objectversion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'modified', 'id', 'feed_id'], name='ctx_nov_modified_t_last_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['type', 'created', 'id', 'feed_id'], name='ctx_nov_created_t_last_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['knowledgebase', 'modified', 'id', 'feed_id'], name='ctx_nov_kb_m_last_idx'),
        ),
        migrations.AddIndex(
            model_name='newobjectvalue',
            index=models.Index(condition=models.Q(('is_dupe', False)), fields=['knowledgebase', 'created', 'id', 'feed_id'], name='ctx_nov_kb_c_last_idx'),
        ),
    ]
